import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import styles from "./index.module.css";

import { UserButton, SignInButton, useUser, useAuth } from "@clerk/nextjs";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  const auth = useAuth();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Simple t3 App with clerk
          </h1>

          <div className={styles.cardRow}>
            <div className={styles.card}>
              {auth.isSignedIn
                ? <UserButton afterSignOutUrl="/" />
                : <><Link href="/sign-in">LOGIN</Link>
                  <SignInButton /></>
              }
              <p>Auth data</p>
              <pre>{JSON.stringify(auth, null, 2)}</pre>
            </div>
          </div>
          <div className={styles.cardRow}>
            <div className={styles.card}>
              <p>User data</p>
              <pre>{JSON.stringify(user, null, 2)}</pre>
            </div>
          </div>

          <p className={styles.showcaseText}>
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
